name = "SUPGChannel"
uuid = "ced8f65f-c3fc-4805-a549-7b1f560fd65c"
authors = ["Bart Janssens <bart@bartjanssens.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
